name: Ready to set .env
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set .env
        run: |
          echo "REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }}" >> .env
          echo "REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}" >> .env
          echo "REACT_APP_CLIENT_SECRET=${{ secrets.REACT_APP_CLIENT_SECRET }}" >> .env
          echo "REACT_APP_INSTALLATION_ID=${{ secrets.REACT_APP_INSTALLATION_ID }}" >> .env
          echo "REACT_APP_PRIVATE_KEY=${{ secrets.REACT_APP_PRIVATE_KEY }}" >> .env
          cat .env
